In [11]:
corpus = open("corpus.txt").read()

In [12]:
corpus

'Next Word Prediction is also called Language Modeling. It is the task of predicting what word comes next. It is one of the fundamental tasks of NLP and has many applications. You might be using it daily when you write texts or emails without realizing it.'

In [13]:
import re
corpus = corpus.lower()
clean_corpus = re.sub('[^a-z0-9]+',' ', corpus)

In [14]:
clean_corpus

'next word prediction is also called language modeling it is the task of predicting what word comes next it is one of the fundamental tasks of nlp and has many applications you might be using it daily when you write texts or emails without realizing it '

In [15]:
#required libraries
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
import numpy as np

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [16]:
tokens = word_tokenize(clean_corpus)
tokens

['next',
 'word',
 'prediction',
 'is',
 'also',
 'called',
 'language',
 'modeling',
 'it',
 'is',
 'the',
 'task',
 'of',
 'predicting',
 'what',
 'word',
 'comes',
 'next',
 'it',
 'is',
 'one',
 'of',
 'the',
 'fundamental',
 'tasks',
 'of',
 'nlp',
 'and',
 'has',
 'many',
 'applications',
 'you',
 'might',
 'be',
 'using',
 'it',
 'daily',
 'when',
 'you',
 'write',
 'texts',
 'or',
 'emails',
 'without',
 'realizing',
 'it']

In [17]:
import pandas as pd
import os
import numpy as np

In [18]:
df = pd.read_csv('medium_data.csv')
df

id                                                url  \
0        1  https://towardsdatascience.com/a-beginners-gui...   
1        2  https://towardsdatascience.com/hands-on-graph-...   
2        3  https://towardsdatascience.com/how-to-use-ggpl...   
3        4  https://towardsdatascience.com/databricks-how-...   
4        5  https://towardsdatascience.com/a-step-by-step-...   
...    ...                                                ...   
6503  6504  https://medium.com/better-marketing/we-vs-i-ho...   
6504  6505  https://medium.com/better-marketing/how-donald...   
6505  6506  https://medium.com/better-marketing/content-an...   
6506  6507  https://medium.com/better-marketing/5-question...   
6507  6508  https://medium.com/better-marketing/how-to-wri...   

                                                  title  \
0     A Beginner’s Guide to Word Embedding with Gens...   
1     Hands-on Graph Neural Networks with PyTorch & ...   
2                          How to Use ggplot2 in Python   
3     Databricks: How to Save Files in CSV on Your L...   
4     A Step-by-Step Implementation of Gradient Desc...   
...                                                 ...   
6503  “We” vs “I” — How Should You Talk About Yourse...   
6504                   How Donald Trump Markets Himself   
6505      Content and Marketing Beyond Mass Consumption   
6506  5 Questions All Copywriters Should Ask Clients...   
6507             How To Write a Good Business Blog Post   

                                               subtitle      image  claps  \
0                                                   NaN      1.png    850   
1                                                   NaN      2.png   1100   
2                      A Grammar of Graphics for Python      3.png    767   
3               When I work on Python projects dealing…     4.jpeg    354   
4                       One example of building neural…     5.jpeg    211   
...                                                 ...        ...    ...   
6503              Basic copywriting choices with a big…   6504.jpg    661   
6504  Lessons from who might be the most popular bra...  6505.jpeg    189   
6505  How to acquire customers without wasting money...   6506.jpg    207   
6506                           Save time and effort by…   6507.jpg    253   
6507                    An A-to-Z guide for non-writers   6508.jpg    147   

     responses  reading_time           publication        date  
0            8             8  Towards Data Science  2019-05-30  
1           11             9  Towards Data Science  2019-05-30  
2            1             5  Towards Data Science  2019-05-30  
3            0             4  Towards Data Science  2019-05-30  
4            3             4  Towards Data Science  2019-05-30  
...        ...           ...                   ...         ...  
6503         6             6      Better Marketing  2019-12-05  
6504         1             5      Better Marketing  2019-12-05  
6505         1             8      Better Marketing  2019-12-05  
6506         2             5      Better Marketing  2019-12-05  
6507         0             9      Better Marketing  2019-12-05  

[6508 rows x 10 columns]

In [19]:
df['title'][3]

'Databricks: How to Save Files in CSV on Your Local\xa0Computer'

In [20]:
df['title'] = df['title'].apply(lambda x: x.replace(u'\xa0',u' '))
df['title'] = df['title'].apply(lambda x: x.replace('\u200a',' '))

In [21]:
df['title'][3]

'Databricks: How to Save Files in CSV on Your Local Computer'

In [23]:
tokenizer = get_tokenizer("basic_english")

In [24]:
def yield_tokens(data_iter):
    for text in data_iter:
        yield tokenizer(text)

In [25]:
tokenizer('Databricks: How to Save Files in CSV on Your Local Computer')

['databricks',
 'how',
 'to',
 'save',
 'files',
 'in',
 'csv',
 'on',
 'your',
 'local',
 'computer']

In [26]:
from torchtext.vocab import build_vocab_from_iterator
vocab = build_vocab_from_iterator(yield_tokens(df['title']), specials=["<unk>", "<pad>"])
vocab.set_default_index(vocab["<unk>"])

In [27]:
vocab(["pytorch",'hello','and'])
vocab.lookup_tokens([ 68,   4,  89])

['write', 'a', 'good']

In [28]:
vocab.lookup_tokens([ 68,   4,  89])

['write', 'a', 'good']

In [29]:
len(vocab)

9002

In [30]:
def made_tokens(train_len,tokens,arr):
    for i in range(train_len,len(tokens)+1):
        seq = tokens[i-train_len:i]
        arr.append(vocab(seq))

In [58]:
data = []
for i in df['title']:
  i=i.lower()
  tokens = tokenizer(i)
  made_tokens(train_len=3,tokens=tokens,arr=data)

In [59]:
data

[[4, 659, 72],
 [659, 72, 2],
 [72, 2, 468],
 [2, 468, 1585],
 [468, 1585, 14],
 [1585, 14, 2876],
 [14, 2876, 8754],
 [2876, 8754, 104],
 [5727, 747, 85],
 [747, 85, 107],
 [85, 107, 14],
 [107, 14, 349],
 [14, 349, 54],
 [349, 54, 349],
 [54, 349, 2061],
 [7, 2, 69],
 [2, 69, 5608],
 [69, 5608, 8],
 [5608, 8, 43],
 [4893, 7, 2],
 [7, 2, 266],
 [2, 266, 1598],
 [266, 1598, 8],
 [1598, 8, 2689],
 [8, 2689, 24],
 [2689, 24, 9],
 [24, 9, 991],
 [9, 991, 268],
 [4, 1024, 485],
 [1024, 485, 5],
 [485, 5, 2068],
 [5, 2068, 1302],
 [2068, 1302, 6],
 [1302, 6, 1509],
 [27, 199, 124],
 [199, 124, 2],
 [124, 2, 461],
 [2, 461, 11],
 [461, 11, 18],
 [11, 18, 366],
 [1634, 296, 8646],
 [124, 2, 6209],
 [2, 6209, 755],
 [6209, 755, 2821],
 [755, 2821, 769],
 [2821, 769, 330],
 [398, 226, 1892],
 [226, 1892, 15],
 [1892, 15, 3],
 [15, 3, 78],
 [3, 78, 57],
 [78, 57, 415],
 [57, 415, 10],
 [23, 99, 44],
 [99, 44, 104],
 [44, 104, 186],
 [104, 186, 1047],
 [186, 1047, 199],
 [1047, 199, 10],
 [796, 4

In [265]:
vocabulary_size = len(vocab)+1
vocabulary_size

2424

In [61]:
train_inputs=np.asarray(data)[:,:-1]

In [62]:
train_inputs


array([[  4, 659],
       [659,  72],
       [ 72,   2],
       ...,
       [  4,  89],
       [ 89,  58],
       [ 58, 662]])

In [63]:
seq_length=train_inputs.shape[1]
seq_length

2

In [64]:
train_targets=np.asarray(data)[:,-1]

In [65]:
train_targets.shape

(41822,)

In [66]:
def to_categorical(y, num_classes):
    """ 1-hot encodes a tensor """
    return np.eye(num_classes, dtype='float32')[y]

train_targets = to_categorical(train_targets, num_classes=vocabulary_size)

In [67]:
train_targets = to_categorical(train_targets, num_classes=vocabulary_size)

In [68]:
train_targets[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [69]:
import torch
from torch.optim import Adam
import torch.nn as nn
     

In [263]:
class lstm(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__()
        #simple lookup table that stores embeddings of a fixed dictionary and size.
        self.embed = nn.Embedding(vocab_size, embed_size)
        
        #lstm 
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers=2, bidirectional=False)
        
        #fully connected layer
        self.linear = nn.Linear(hidden_size*seq_length,vocab_size)
        self.fun = nn.Softmax()
    
    def forward(self, input_word):
        #input sequence to embeddings
        embedded = self.embed(input_word)
        
        #passing the embedding to lstm model
        output, hidden = self.lstm(embedded)
        
        #reshaping
        output=output.view(output.size(0), -1)
        
        #fully connected layer
        output = self.linear(output)
        output = self.fun(output)
        
        return output,hidden


In [264]:
model=lstm(vocab_size=)

NameError: name 'vocabulary_size' is not defined

In [97]:

model


lstm(
  (embed): Embedding(9003, 128)
  (lstm): LSTM(128, 256, num_layers=2)
  (linear): Linear(in_features=512, out_features=9003, bias=True)
)

In [98]:
optimizer= Adam(model.parameters(), lr=0.07)

#loss
criterion = nn.BCEWithLogitsLoss()

In [99]:
train_targets

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [100]:
def train(epoch):
    #set the model to train
    model.train()
    tr_loss=0    
    
    #clearing the Gradients 
    optimizer.zero_grad()
    
    #predict the output
    y_pred, (state_h, state_c) = model(torch.from_numpy(train_inputs))
    
    #compute the loss
    loss=criterion(y_pred,torch.from_numpy(train_targets))
    losses.append(loss)
    
    #backpropagate
    loss.backward()

    #update the parameters
    optimizer.step()
    tr_loss = loss.item()

    print("Epoch : ",epoch,"loss : ",loss)

no_epoch=4
losses=[]
for epoch in range(1,no_epoch+1):
    train(epoch)

In [102]:
train_inputs.shape

(41822, 2)

In [103]:
train_inputs[0].reshape(1,-1).shape

(1, 2)

In [104]:
train_inputs

array([[  4, 659],
       [659,  72],
       [ 72,   2],
       ...,
       [  4,  89],
       [ 89,  58],
       [ 58, 662]])

In [123]:
vocab(['how', 'to'])

[7, 2]

In [126]:
predict_next_word('jk')

17


In [127]:
vocab.lookup_tokens([17])

['—']

In [125]:
def predict_next_word(text):
    #set the model to evaluation
    model.eval()

    #converting to array
    with torch.no_grad():
        #converting to tensor
        
        #predicting the output
        predict,(hidden,cell)=model(torch.from_numpy(np.asarray([7, 2]).reshape(1,-1)))
    
    #applying the softmax layer
    softmax = torch.exp(predict)
    prob = list(softmax.numpy())
    
    #index of the predict word
    predictions = np.argmax(prob)

    print(predictions)

In [116]:
torch.from_numpy(train_inputs[0])

tensor([  4, 659], dtype=torch.int32)

In [278]:
input_text="next word"

In [279]:
predict_next_word(input_text)

25


In [280]:
# Save Files in

In [281]:

# vocab.lookup_tokens([468, 1585, 14])

[172, 468, 766]

In [283]:
vocab.lookup_tokens([25])

['learning']

In [132]:
###########

In [133]:
import pandas as pd
import numpy as np
import string, os
import warnings

import torch

warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore', category=FutureWarning)

In [134]:
curr_dir = './comments/'
all_headlines = []
for filename in os.listdir(curr_dir):
    if 'Articles' in filename:
        article_df = pd.read_csv(curr_dir + filename)
        all_headlines.extend(list(article_df.headline.values))
        break

In [135]:
all_headlines = [line for line in all_headlines if line!= "Unknown"]
print(all_headlines[:10])

['Finding an Expansive View  of a Forgotten People in Niger', 'And Now,  the Dreaded Trump Curse', 'Venezuela’s Descent Into Dictatorship', 'Stain Permeates Basketball Blue Blood', 'Taking Things for Granted', 'The Caged Beast Awakens', 'An Ever-Unfolding Story', 'O’Reilly Thrives as Settlements Add Up', 'Mouse Infestation', 'Divide in G.O.P. Now Threatens Trump Tax Plan']


In [136]:
def clean_text(txt):
    txt = "".join(t for t in txt if t not in string.punctuation).lower()
    txt = txt.encode("utf8").decode("ascii",'ignore')
    return txt

In [137]:
corpus = [clean_text(x) for x in all_headlines]
print(corpus[:14])

['finding an expansive view  of a forgotten people in niger', 'and now  the dreaded trump curse', 'venezuelas descent into dictatorship', 'stain permeates basketball blue blood', 'taking things for granted', 'the caged beast awakens', 'an everunfolding story', 'oreilly thrives as settlements add up', 'mouse infestation', 'divide in gop now threatens trump tax plan', 'variety puzzle acrostic', 'they can hit a ball 400 feet but play catch thats tricky', 'in trump country shock at trump budget cuts', 'why is this hate different from all other hate']


In [138]:
from torchtext.data import get_tokenizer
tokenizer = get_tokenizer("basic_english")

In [139]:
tokenizer(corpus[1])

['and', 'now', 'the', 'dreaded', 'trump', 'curse']

In [140]:
def yield_tokens(data_iter):
    for text in data_iter:
        yield tokenizer(text)

In [141]:
from torchtext.vocab import build_vocab_from_iterator
vocab = build_vocab_from_iterator(yield_tokens(corpus), specials=["<unk>", "<pad>"])
vocab.set_default_index(vocab["<unk>"])

In [142]:
def get_sequence_of_token(corpus):
    input_sequnces = []
    for line in corpus:
        token_list = tokenizer(line)
        for i in range(1,len(token_list)):
            n_gram_sequence = token_list[:i+1]
            _n_gram_sequence  = vocab(n_gram_sequence)
            input_sequnces.append(_n_gram_sequence)
    return input_sequnces

In [143]:
inp_seq = get_sequence_of_token(corpus=corpus)

In [145]:
total_words = len(vocab)
total_words

2423

In [146]:
def to_categorical(y, num_classes):
    """ 1-hot encodes a tensor """
    return np.eye(num_classes, dtype='float32')[y]

In [147]:
def pad_sequences_torch(arr,maxlen):
    seq_len = len(arr)
    padding = (maxlen-seq_len,0)
    pad = torch.nn.ZeroPad2d(padding)
    return pad(torch.tensor(arr))

In [148]:
def generate_padded_sequences(inp_seq):
    max_sequence_len = max([len(x) for x in inp_seq])
    res_1 = [pad_sequences_torch(i,max_sequence_len) for i in inp_seq]
    input_sequences = np.array(res_1)
    
    predictors, label = input_sequences[:,:-1],input_sequences[:,-1]
    label = to_categorical(label, num_classes=total_words)
    return predictors, label, max_sequence_len

In [149]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim

In [150]:
len(inp_seq)

4806

In [152]:
class CreateDataset(Dataset):
    def __init__(self, inp_seq):
        self.inp_seq = inp_seq
        max_sequence_len = max([len(x) for x in self.inp_seq])
        res_1 = [pad_sequences_torch(i,max_sequence_len) for i in self.inp_seq]
        self.input_sequences = np.array(res_1)
         
    def __getitem__(self, index):
        
        fetures, label = self.input_sequences[index,:-1],self.input_sequences[index,-1]
        label = to_categorical(label, num_classes=total_words)
        return fetures, label
    
    def __len__(self):
        return len(self.inp_seq)

In [153]:
train_dataset = CreateDataset(inp_seq=inp_seq)
train_loader = DataLoader(train_dataset, shuffle=True)

In [154]:
example = iter(train_loader)
feature, label = next(example)

In [158]:
feature[0]

tensor([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,   20, 2397, 1222])

In [161]:
label[0]

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [198]:
# embed(feature[0])
embed(feature[0])[0]

tensor([ 1.1682e+00,  3.6346e-01, -1.6031e+00, -1.2317e+00, -1.2398e+00,
        -2.1165e-01, -9.1523e-01, -1.4533e+00, -3.4596e-01, -1.6536e+00,
         8.5156e-01, -1.1065e+00, -7.8382e-01,  6.3386e-01,  9.7227e-01,
        -8.7601e-01, -5.6772e-01, -1.0541e+00, -1.4056e-01, -2.8671e-01,
        -4.3447e-01, -7.7243e-01, -2.0317e-01, -5.0626e-01,  1.2863e-01,
        -1.7923e-01,  3.4295e-01,  5.1880e-01, -1.1758e+00, -1.4124e+00,
         4.1626e-01, -1.3540e-01,  2.6110e-01,  3.1680e-01, -2.0731e+00,
        -1.3371e-01,  2.3793e-01,  9.4596e-01,  6.5432e-01, -1.0252e-01,
        -4.5700e-01,  1.4070e+00, -4.2537e-01,  6.4142e-01, -9.5792e-01,
        -7.4139e-01,  7.7897e-01,  4.5210e-01,  1.3707e+00, -5.5293e-01,
         8.1858e-01, -3.2324e-01,  1.4070e+00, -1.0768e+00,  1.0443e-03,
         8.6933e-01,  7.4814e-01,  1.6104e+00, -8.2147e-01,  7.1884e-01,
        -3.2226e-01, -1.6827e-01,  1.3920e-01, -2.0459e+00,  1.0289e+00,
        -7.8053e-02,  6.8039e-01,  8.2639e-02, -1.8

In [179]:
embed(torch.tensor(vocab(tokenizer(corpus[1])))).size()

torch.Size([6, 200])

In [119]:
pred, label, max_seq = generate_padded_sequences(inp_seq)

In [120]:
pred

array([[   0,    0,    0, ...,    0,    0,  185],
       [   0,    0,    0, ...,    0,  185,   18],
       [   0,    0,    0, ...,  185,   18, 1219],
       ...,
       [   0,    0,    0, ...,  101, 2180,   57],
       [   0,    0,    0, ..., 2180,   57,  347],
       [   0,    0,    0, ...,   57,  347,   95]], dtype=int64)

In [121]:
label.shape

(4806, 2423)

In [122]:
import torch
from torch.optim import Adam
import torch.nn as nn

In [123]:
a = nn.Embedding(total_words, 10)
a

Embedding(2423, 10)

In [124]:
inp_seq[0]

[185, 18]

In [125]:
class lstm(nn.Module):
    def __init__(self, vocab_size, embed_size=10, hidden_size=100):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_size)
        
        #lstm 
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers=1, bidirectional=False)
        
        #fully connected layer
        self.linear = nn.Linear(hidden_size*max_seq,vocab_size)
        self.fun = nn.Softmax()
    
    def forward(self, input_word):
        #input sequence to embeddings
        embedded = self.embed(input_word)
        
        #passing the embedding to lstm model
        output, hidden = self.lstm(embedded)
        
        #reshaping
        output=output.view(output.size(0), -1)
        
        #fully connected layer
        output = self.linear(output)
        output = self.fun(output)
        
        return output,hidden

In [126]:
import torch
import torch.nn as nn
import torch.nn.functional as F


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [127]:
train_on_gpu = False

In [271]:
import torch.nn as nn

class RNN(nn.Module):
    
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, dropout=0.5):
        super(RNN, self).__init__()
      
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, dropout=dropout, batch_first=True)
        
        
        self.vocab_size = vocab_size
        self.output_size = output_size
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        
     
        self.fc = nn.Linear(hidden_dim, output_size)
    
    
    def forward(self, x, hidden):
        batch_size = x.size(0)
        x=x.long()
        
        # embedding and lstm_out 
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
        
        # stack up lstm layers
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        # dropout, fc layer and final sigmoid layer
        out = self.fc(lstm_out)
        
        # reshaping out layer to batch_size * seq_length * output_size
        out = out.view(batch_size, -1, self.output_size)
        print(out.size())
        # return last batch
        out = out[:, -1]

        # return one batch of output word scores and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        weights = next(self.parameters()).data
        if(train_on_gpu):
            hidden = (weights.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(), 
                     weights.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weights.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                     weights.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden

In [266]:
def forward_back_prop(rnn, optimizer, criterion, inp, target, hidden):
   
    h = tuple([each.data for each in hidden])
    
    rnn.zero_grad()
  
    inputs, targets = inp.to(device), target.to(device)
    
    output, h = rnn(inputs, h)
    
    loss = criterion(output, targets)
    
    # perform backpropagation and optimization
    loss.backward()
    nn.utils.clip_grad_norm_(rnn.parameters(), 5)
    optimizer.step()

    # return the loss over a batch and the hidden state produced by our model
    return loss.item(), h

In [267]:
def train_rnn(rnn, batch_size, optimizer, criterion, n_epochs, show_every_n_batches=100):
    batch_losses = []
    
    rnn.train()

    print("Training for %d epoch(s)..." % n_epochs)
    for epoch_i in range(1, n_epochs + 1):
        
        # initialize hidden state
        hidden = rnn.init_hidden(batch_size)
        
        for batch_i, (inputs, labels) in enumerate(train_loader, 1):
            
            # make sure you iterate over completely full batches, only
            n_batches = len(train_loader.dataset)//batch_size
            if(batch_i > n_batches):
                break
            
            # forward, back prop
            loss, hidden = forward_back_prop(rnn, optimizer, criterion, inputs, labels, hidden)          
            # record loss
            batch_losses.append(loss)

            # printing loss stats
            if batch_i % show_every_n_batches == 0:
                print('Epoch: {:>4}/{:<4}  Loss: {}\n'.format(
                    epoch_i, n_epochs, np.average(batch_losses)))
                batch_losses = []
            break
    # returns a trained rnn
    return rnn

In [268]:
sequence_length = 18  # of words in a sequence
# Batch Size
batch_size = 1

# data loader - do not change

In [269]:
num_epochs = 10
# Learning Rate
learning_rate = 0.001

# Model parameters
# Vocab size
vocab_size = len(vocab)
# Output size
output_size = vocab_size
# Embedding Dimension
embedding_dim = 200
# Hidden Dimension
hidden_dim = 250
# Number of RNN Layers
n_layers = 2

# Show stats for every n number of batches
show_every_n_batches = 500

In [270]:
rnn = RNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers, dropout=0.5)
print(rnn)
if train_on_gpu:
    rnn.cuda()

# defining loss and optimization functions for training
optimizer = torch.optim.Adam(rnn.parameters(), lr=learning_rate)
criterion = nn.BCEWithLogitsLoss()

# training the model
trained_rnn = train_rnn(rnn, batch_size, optimizer, criterion, num_epochs, show_every_n_batches)

AssertionError: Padding_idx must be within num_embeddings

In [387]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [53]:
hidden = rnn.init_hidden(batch_size)
h = tuple([each.data for each in hidden])


In [91]:
token_list = tokenizer('united states')
text  = vocab(token_list)
text = pad_sequences_torch(text,18)
text

tensor([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  346, 2153])

In [92]:
output = rnn(text.reshape(1,-1),h)

In [131]:
torch.argmax(output[-1][0][0][0])

tensor(156)

In [95]:
vocab.lookup_tokens([156])

['money']

In [77]:
def train(label, input):
    model.train()
    model.zero_grad()
    model.hidden = model.init_hidden()
    print(input)
    output = model(input)[-1]
    loss = criterion(output.unsqueeze(0), label)
    loss.backward()
    
    optimizer.step()
    return output.unsqueeze(0), loss.item()

In [405]:
criterion = nn.BCEWithLogitsLoss()

epochs = 1
learning_rate = 0.04 # If you set this too high, it might explode. If too low, it might not learn
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [406]:
for epoch in range(epochs):

    current_loss  = 0

    for i, (features, labels) in enumerate(train_loader):
       
        features = features.to(device)
        labels = labels.to(device)
        
        out, loss = train(labels,features)

    current_loss += loss
    
    print(f'Epoch: {epoch} , Loss {current_loss}')

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 213,  59]])
tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 14]])
tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 27, 20,  3]])
tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0, 2375]])
tensor([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0, 1193, 2256,   66, 1357]])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 128,  91,   8,   6,
          27, 206, 135,  34]])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  12, 815]])
tensor([[   0,    0,    0,    0,    0,    0,   43, 1111,   27,  120,  516,   66,
          525,  129,    7,  112,   66,  695]])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 106, 529]])
tensor([[ 

KeyboardInterrupt: 

In [392]:
def pad_sequences_torch(arr,maxlen):
    seq_len = len(arr)
    padding = (maxlen-seq_len,0)
    pad = torch.nn.ZeroPad2d(padding)
    return pad(torch.tensor(arr))

In [79]:
token_list = tokenizer('venezuelas descent into')
text  = vocab(token_list)
text = pad_sequences_torch(text,18)
text

tensor([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0, 2341, 1104,  148])

In [80]:
model.hidden = model.init_hidden()
output = model(text.reshape(1,-1))

NameError: name 'model' is not defined

In [468]:
torch.argmax(output[-1])

tensor(2)

In [470]:
vocab.lookup_tokens([2])

['the']